### ISSUE TITLE
TypeInitializationException on Linux 18.0.4

### ISSUE THREAD

**Issue by ernest-morariu** [pauldotknopf/Qml.Net.Examples#12]
I tried the project Features on my development machine Windows 10-64 bit.
When I launch it from Visual Studio 2017, I get the following error message in the console window:
"QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x080010106)""
The error message appears on the line 13, `using (var application = new QGuiApplication(args)).` 

However, this error doesn't brake the application; the application continues and works fine. 

Then I tried it to on Linux 18.0.4, the one from Windows Store. I used the following publish configuration in Visual Studio:
![image](https://user-images.githubusercontent.com/16528481/52483325-e608fd80-2bb3-11e9-9eca-5a84cf755c4b.png)

When I launched the application I got TypeInitializationException:
![image](https://user-images.githubusercontent.com/16528481/52483696-d4742580-2bb4-11e9-982d-b2a2138e407d.png)

Then I tried some other publish configurations, but none of them was successful. 

Then I commented out the line QQuickStyle.SetStyle("Material"), but I got the same exception(of course with a different stack trace).

Then I created a "Hello World" console application that targets the same netcoreapp2.2. I wanted to be sure that I installed correctly the .netcore 2.2 on Linux. The application works fine on Linux.

Is there something I am doing wrong?

**Comment by pauldotknopf** [comment]
Nothing wrong, this happens with a pure Qt app as well.

In my experience, that error has been harmless.

**Comment by ernest-morariu** [comment]
Thank you for your reply. 
You didn't say anything about the TypeInitializationException on Linux? Do you have any idea what would cause that issue?

**Comment by pauldotknopf** [comment]
Is this Ubuntu using WSL?

**Comment by ernest-morariu** [comment]
Yes, it's WSL. I installed it from Windows Store.

**Comment by pauldotknopf** [comment]
WSL doesn't support GUI apps (without some hacking). You'll have to run Qml.Net on a native Linux box.

**Comment by ernest-morariu** [comment]
Thank you very much.

**Comment by Ticky-Ticky** [comment]
I have the same error on Ubuntu, but I'm not using WSL. What else can be a reason for such an error?

**Comment by pauldotknopf** [comment]
If you are interested in a TeamViewer session, email me at pauldotknopf at gmail.

Otherwise, set ```LD_DEBUG=all```, run again, and give me the output.
