### ISSUE TITLE
How to package/release this application

### ISSUE THREAD

**Issue by geocine** [pauldotknopf/Qml.Net.Examples#21]
How do I properly package/release this application. It outputs an executable but when I open that it looks for `Main.qml` so I have to copy that to the Output directory , also it opens a console.

1. How can I package it in such a way that when I click the executable , it doesn't open a console? 
   > Edit: I found the answer here https://github.com/qmlnet/qmlnet/issues/80

2. How do I bunde the QML files inside the executable?

**Comment by pauldotknopf** [comment]
When using .NET as your entry point, it's a little involved, to the point that I think it isn't usable. The QML files have to be correctly structured in the current working directory, and Qt has to be installed in your path, or make sure it is in one of [these](https://github.com/qmlnet/qmlnet/blob/b4becbea925166adcc06c2ed800b77c7269758a5/src/net/Qml.Net/Runtimes/RuntimeManager.Discovery.cs) directories. The qt runtimes can be found [here](https://github.com/qmlnet/qt-runtimes/releases).

The easiest solution by far is to use Qt as your entry point. Then you'll have a single executable with all your QML resources compiled within. Then, you just pass it a path to your .NET libraries. See [here](https://qmlnet.github.io/setup/unmanaged-hosting/).
