### ISSUE TITLE
Switch QQmlApplicationEngine for Qml in Program.cs

### ISSUE THREAD

**Issue by MaxMommersteeg** [pauldotknopf/Qml.Net.Examples#4]
The `Qml` type is used in the https://github.com/qmlnet/qmlnet repository and described on the project's wiki.

This samples project still uses `QQmlApplicationEngine`. We should change it to `Qml`.

Will created a PR when I have some time left today.

Should wait until `Qml` is available from the NuGet package.

**Comment by pauldotknopf** [comment]
All updated/fixed in master.

Thanks!
