### ISSUE TITLE
How to close the black console window

### ISSUE THREAD

**Issue by hessonsu** [pauldotknopf/Qml.Net.Examples#8]
How to close the black console window

**Comment by MaxMommersteeg** [comment]
Following issue might be helpful to you: https://github.com/qmlnet/qmlnet/issues/80

You are running on Windows too right?

**Comment by hessonsu** [comment]
Yes, running on Windows.
I tried to solve this problem using the NuGet package.
Install-Package NSubsys.
Thanks.
